name: HMDA Unit Tests

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
          distribution: temurin
          java-version: adopt@1.13.0-2

    - name: Run sbt tests
      run: |
        sbt test
