name: HMDA Unit Tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Sbt Tests
        run: |
          sbt test
          echo "::set-output name=summary::This is the summary message"
          echo "GITHUB_STEP_SUMMARY=This is the log message" >> $GITHUB_ENV




