name: HMDA Unit Tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run FilingPersistenceSpec tests
        run: |
          sbt "project hmda-platform" "testOnly *FilingPersistenceSpec" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Run LarComponentSpec tests
        run: |
          sbt "project hmda-analytics" "testOnly *LarComponentSpec" 2>&1 | tee -a log-file
        continue-on-error: true


      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 13 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi
