name: HMDA Unit Tests

on:
  pull_request:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run sbt tests
      run: |
        sbt test
